# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            uniDev
tagline:          "uniDev's blog"
description: >
  Hyeonseung Bae<br/>
  Back-end Infrastructure.
url:              http://bae-unidev.github.io
baseurl:          /

paginate:         10
encoding: utf-8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bae-unidev
